### ISSUE TITLE
Plugin not working with Nova v4.32.10

### ISSUE THREAD

**Issue by Eli-Pez** [Muetze42/nova-resource-card#6]
Since the update of Nova to v4.32.10 the package works no more.

<img width="1283" alt="error-nova-cards" src="https://github.com/Muetze42/nova-resource-card/assets/145749363/069d93ae-1b33-4d61-8716-02d098d62e03">

The error:
<img width="452" alt="Screenshot 2023-12-20 alle 08 39 58" src="https://github.com/Muetze42/nova-resource-card/assets/145749363/1cc30a46-5570-4a9b-981f-73256a43d9f7">

**Comment by Muetze42** [comment]
A quick sign of life. I have a busy schedule, but I'll be looking at the package this weekend.

**Comment by Muetze42** [comment]
https://github.com/Muetze42/nova-resource-card/releases/tag/v1.0.2

**Comment by Eli-Pez** [comment]
Great! I run "composer update" and it works now! Thank you for your quick response.

**Comment by Muetze42** [comment]
With [Nova Watch](https://github.com/Muetze42/nova-watch) I already have a notification system that notifies me when an update is coming so that I can react more quickly to Nova updates.

Unfortunately, I don't always know which Nova resource I'm using in which package. That will come next. Notifications for packages...
